# Generated by Django 4.0.3 on 2022-07-12 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='stared_user',
            field=models.ManyToManyField(blank=True, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selection',
            name='items',
            field=models.ManyToManyField(to='music.track'),
        ),
        migrations.AddField(
            model_name='selection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
